{{- if and (eq (include "common.tls.require-secure-edge" $) "true") (not .Values.certificateResources.tlsSecretName) -}}

{{- $issuerRef := .Values.certificateResources.certificateRequest.issuerRef -}}

{{- if not $issuerRef -}}
  {{- fail "A value for .certificateResources.certificateRequest.issuerRef is required to create the certificate request" -}}
{{- end -}}

{{- $component := "proxy" -}}
{{- $certificateName := (printf "%s-certificate" (include "proxy.name" $)) -}}
{{- $secretName := (printf "%s-tls" (include "proxy.name" .)) -}}
{{- $jksSecretName := (coalesce .Values.certificateResources.jksPasswordSecretName (printf "%s-jks" (include "proxy.name" $))) -}}

{{- $commonName := (include "proxy.fullname" .) -}}

{{- $dnsNames := list -}}
{{- $dnsNames = append $dnsNames "127.0.0.1" -}}
{{- $dnsNames = append $dnsNames "localhost" -}}

{{- if .Values.global.proxy.dnsName -}}
  {{- $dnsNames = append $dnsNames .Values.global.proxy.dnsName -}}
{{- else -}}
  {{- $dnsNames = append $dnsNames (printf "%s.%s.svc.%s" (printf "%s-service" (include "proxy.name" .)) (include "common.names.namespace" .) (include "common.names.domain" .)) -}}
{{- end -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificateName | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "proxy.name" .) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  commonName: {{ $commonName | quote }}
  dnsNames: {{- include "common.tplvalues.render" ( dict "value" $dnsNames "context" $ ) | nindent 4 }}
  secretName: {{ $secretName | quote }}
  secretTemplate:
    annotations:
      {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 6 }}
    labels:
      {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 6 }}
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: jks-password
        name: {{ $jksSecretName | quote }}
  {{- if .Values.certificateResources.certificateRequest.renewBefore }}
  renewBefore: {{ int .Values.certificateResources.certificateRequest.renewBefore }}
  {{- end }}
  {{- if .Values.certificateResources.certificateRequest.duration }}
  duration: {{ int .Values.certificateResources.certificateRequest.duration }}
  {{- end }}
  {{- if .Values.certificateResources.certificateRequest.subject.organizations }}
  subject:
    organizations: {{ include "common.tplvalues.render" ( dict "value" .Values.certificateResources.certificateRequest.subject.organizations "context" $ ) }}
  {{- end }}
  {{- if .Values.certificateResources.certificateRequest.privateKey }}
  privateKey:
    {{- include "common.tplvalues.render" ( dict "value" .Values.certificateResources.certificateRequest.privateKey "context" $ ) | nindent 4 }}
  {{- end }}
  issuerRef:
    {{ include "common.tplvalues.render" ( dict "value" $issuerRef "context" $ ) | nindent 4 }}
{{- end }}