{
 "title": "Pulsar / Bookkeeper READ USE",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "DbLedgerStorage Reads Time Spent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_entry_sum[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Read Thread Pool Time Spent",
   "type": "graph",
   "description": "Time spent by the read thread pool executing requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_BookieReadThreadPool_task_execution_sum[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Read thread pool task queues length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_0) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_1) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_2) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_3) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_4) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_5) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_6) by (pod)"
    },
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_queue_7) by (pod)"
    }
   ]
  },
  {
   "title": "Read thread pool queue p99 time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_BookieReadThreadPool_task_queued{success=\"true\",quantile=\"0.99\"}) by (pod)"
    }
   ]
  }
 ]
}