{
 "title": "Pulsar / JVM",
 "description": "JVM Related Metrics",
 "tags": [ "pulsar" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "jvm_memory_bytes_used{cluster=~\".+\"}"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "jvm_memory_bytes_used{job=~\".+\"}"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "jvm_memory_bytes_used{job=~\"$job\", pod=~\".+\"}"
   }
  ]
 },
 "panels": [
  { "title": "$job - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{pod=~\"$instance\"}[60s]) * 100\n\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=~\"$instance\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{pod=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{pod=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{pod=~\"$instance\"}[60s]))",
     "legendFormat": "Pause"
    }
   ]
  },
  { "title": "$job - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{pod=~\"$instance\"}[60s]) * 100\n\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=~\"$instance\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{pod=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{pod=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{pod=~\"$instance\"}[60s]))",
     "legendFormat": "Pause"
    }
   ]
  },
  { "title": "$job - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{pod=~\"$instance\"}[60s]) * 100\n\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=~\"$instance\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{pod=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{pod=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{pod=~\"$instance\"}[60s]))",
     "legendFormat": "Pause"
    }
   ]
  },
  { "title": "$job - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{pod=~\"$instance\"}[60s]) * 100\n\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=~\"$instance\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{pod=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{pod=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{pod=~\"$instance\"}[60s]))",
     "legendFormat": "Pause"
    }
   ]
  }
 ]
}