{
 "title": "ZooKeeper by Prometheus",
 "description": "ZooKeeper Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "znode_count", "legendFormat": "{{instance}} znode_count" }
   ]
  },
  {
   "title": "ephemerals_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ephemerals_count", "legendFormat": "{{instance}} ephemerals_count" }
   ]
  },
  {
   "title": "global_sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "global_sessions", "legendFormat": "{{instance}}  global_sessions" }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "local_sessions", "legendFormat": "{{instance}} local_sessions " }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_sent", "legendFormat": "{{instance}} packets_sent" }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_received", "legendFormat": "{{instance}} packets_received" }
   ]
  },
  {
   "title": "connection_drop_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_drop_count",
     "legendFormat": "{{instance}} connection_drop_count"
    }
   ]
  },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests",
     "legendFormat": "{{instance}} outstanding_requests"
    }
   ]
  },
  {
   "title": "connection_rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_rejected",
     "legendFormat": "{{instance}} connection_rejected"
    }
   ]
  },
  {
   "title": "connection_drop_probability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_drop_probability",
     "legendFormat": "{{instance}} connection_drop_probability"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrecoverable_error_count",
     "legendFormat": "{{instance}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ensemble_auth_fail",
     "legendFormat": "{{instance}} ensemble_auth_fail"
    },
    {
     "expr": "ensemble_auth_success",
     "legendFormat": "{{instance}} ensemble_auth_success"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "startup_snap_load_time",
     "legendFormat": "{{instance}} startup_snap_load_time-{{quantile}}"
    },
    {
     "expr": "startup_snap_load_time_count",
     "legendFormat": "{{instance}} startup_snap_load_time_count"
    },
    {
     "expr": "startup_snap_load_time_sum",
     "legendFormat": "{{instance}} startup_snap_load_time_sum"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "approximate_data_size", "legendFormat": "approximate_data_size" }
   ]
  },
  {
   "title": "bytes_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_received_count",
     "legendFormat": "{{instance}} bytes_received_count"
    }
   ]
  },
  { "title": "Quorum/Leader Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "election_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "election_time", "legendFormat": "{{instance}} election_time" },
    {
     "expr": "election_time_count",
     "legendFormat": "{{instance}} election_time_count"
    },
    { "expr": "election_time_sum", "legendFormat": "{{instance}} election_time_sum" },
    {
     "expr": "election_time_sum/election_time_count",
     "legendFormat": "{{instance}} election_avg_time"
    }
   ]
  },
  {
   "title": "quorum_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "quorum_size", "legendFormat": "{{instance}} quorum_size" },
    { "expr": "learners", "legendFormat": "{{instance}} learners" },
    {
     "expr": "synced_non_voting_followers",
     "legendFormat": "{{instance}} synced_non_voting_followers"
    }
   ]
  },
  {
   "title": "local_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "local_write_committed_time_ms",
     "legendFormat": "{{instance}} local_write_committed_time_ms-{{quantile}}"
    },
    {
     "expr": "local_write_committed_time_ms_count",
     "legendFormat": "{{instance}} local_write_committed_time_ms_count"
    },
    {
     "expr": "local_write_committed_time_ms_sum",
     "legendFormat": "{{instance}} local_write_committed_time_ms_sum"
    }
   ]
  },
  {
   "title": "server_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_write_committed_time_ms",
     "legendFormat": "{{instance}} server_write_committed_time_ms-{{quantile}}"
    }
   ]
  },
  {
   "title": "learner_commit_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "learner_commit_received_count",
     "legendFormat": "{{instance}} learner_commit_received_count"
    }
   ]
  },
  {
   "title": "leader_uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "leader_uptime", "legendFormat": "{{instance}} leader_uptime" },
    { "expr": "uptime", "legendFormat": "{{instance}} uptime" }
   ]
  },
  {
   "title": "commit_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "commit_count", "legendFormat": "{{instance}} commit_count" }
   ]
  },
  {
   "title": "proposal_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "proposal_count", "legendFormat": "{{instance}} proposal_count" }
   ]
  },
  { "title": "session/watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "close_session_prep_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "close_session_prep_time",
     "legendFormat": "{{instance}} close_session_prep_time"
    }
   ]
  },
  {
   "title": "pending_session_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pending_session_queue_size",
     "legendFormat": "{{instance}} pending_session_queue_size_count-{{quantile}}"
    },
    {
     "expr": "pending_session_queue_size_count",
     "legendFormat": "{{instance}} pending_session_queue_size_count"
    },
    {
     "expr": "pending_session_queue_size_sum",
     "legendFormat": "{{instance}} pending_session_queue_size_sum"
    }
   ]
  },
  {
   "title": "reads_after_write_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reads_after_write_in_session_queue_count",
     "legendFormat": "{{instance}} reads_after_write_in_session_queue_count"
    },
    {
     "expr": "reads_after_write_in_session_queue_sum",
     "legendFormat": "{{instance}} reads_after_write_in_session_queue_sum"
    },
    {
     "expr": "reads_after_write_in_session_queue",
     "legendFormat": "{{instance}} reads_after_write_in_session_queue"
    }
   ]
  },
  {
   "title": "reads_issued_from_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reads_issued_from_session_queue",
     "legendFormat": "{{instance}} reads_issued_from_session_queue-{{quantile}}"
    },
    {
     "expr": "reads_issued_from_session_queue_count",
     "legendFormat": "{{instance}} reads_issued_from_session_queue_count"
    },
    {
     "expr": "reads_issued_from_session_queue_sum",
     "legendFormat": "{{instance}} reads_issued_from_session_queue_sum"
    }
   ]
  },
  {
   "title": "requests_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_in_session_queue",
     "legendFormat": "{{instance}} requests_in_session_queue-{{quantile}}"
    },
    {
     "expr": "requests_in_session_queue_count",
     "legendFormat": "{{instance}} requests_in_session_queue_count"
    },
    {
     "expr": "requests_in_session_queue_sum",
     "legendFormat": "{{instance}} requests_in_session_queue_sum"
    }
   ]
  },
  {
   "title": "session_queues_drained",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "session_queues_drained",
     "legendFormat": "{{instance}} session_queues_drained-{{quantile}}"
    },
    {
     "expr": "session_queues_drained_count",
     "legendFormat": "{{instance}} session_queues_drained_count"
    },
    {
     "expr": "session_queues_drained_sum",
     "legendFormat": "{{instance}} session_queues_drained_sum"
    }
   ]
  },
  {
   "title": "stale_sessions_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stale_sessions_expired",
     "legendFormat": "{{instance}} stale_sessions_expired"
    }
   ]
  },
  {
   "title": "revalidate_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "revalidate_count", "legendFormat": "{{instance}} revalidate_count" }
   ]
  },
  {
   "title": "reads_issued_from_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reads_issued_from_session_queue",
     "legendFormat": "{{instance}} reads_issued_from_session_queue"
    },
    {
     "expr": "reads_issued_from_session_queue_count",
     "legendFormat": "{{instance}} reads_issued_from_session_queue_count"
    },
    {
     "expr": "reads_issued_from_session_queue_sum",
     "legendFormat": "{{instance}} reads_issued_from_session_queue_sum"
    }
   ]
  },
  {
   "title": "add_dead_watcher_stall_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "add_dead_watcher_stall_time",
     "legendFormat": "{{instance}} add_dead_watcher_stall_time"
    }
   ]
  },
  {
   "title": "sessionless_connections_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sessionless_connections_expired",
     "legendFormat": "{{instance}} sessionless_connections_expired"
    }
   ]
  },
  {
   "title": "node_deleted_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_deleted_watch_count",
     "legendFormat": "{{instance}} node_deleted_watch_count-{{quantile}}"
    },
    {
     "expr": "node_deleted_watch_count_count",
     "legendFormat": "{{instance}} node_deleted_watch_count_count"
    },
    {
     "expr": "node_deleted_watch_count_sum",
     "legendFormat": "{{instance}} node_deleted_watch_count_sum"
    }
   ]
  },
  { "title": "disk/snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "fsynctime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fsynctime", "legendFormat": "{{instance}} fsynctime" },
    { "expr": "fsynctime_count", "legendFormat": "{{instance}} fsynctime_count" },
    { "expr": "fsynctime_sum", "legendFormat": "{{instance}} fsynctime_sum" }
   ]
  },
  {
   "title": "file_descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "open_file_descriptor_count",
     "legendFormat": "{{instance}} open_file_descriptor_count"
    },
    { "expr": "process_max_fds", "legendFormat": "{{instance}} process_max_fds" }
   ]
  },
  {
   "title": "snapshot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "snapshottime", "legendFormat": "{{instance}} snapshottime" },
    {
     "expr": "snapshottime_count",
     "legendFormat": "{{instance}} snapshottime_count"
    },
    { "expr": "snapshottime_sum", "legendFormat": "{{instance}} snapshottime_sum" }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "client_response_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_client_response_size",
     "legendFormat": "{{instance}} last_client_response_size"
    },
    {
     "expr": "min_client_response_size",
     "legendFormat": "{{instance}} min_client_response_size"
    }
   ]
  },
  { "title": "prep_processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "prep_processor_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prep_processor_queue_time_ms",
     "legendFormat": "{{instance}} prep_processor_queue_time_ms-{{quantile}}"
    },
    {
     "expr": "prep_processor_queue_time_ms_count",
     "legendFormat": "{{instance}} prep_processor_queue_time_ms_count"
    },
    {
     "expr": "prep_processor_queue_time_ms_sum",
     "legendFormat": "{{instance}} prep_processor_queue_time_ms_sum"
    }
   ]
  },
  {
   "title": "outstanding_changes_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_changes_queued",
     "legendFormat": "{{instance}} outstanding_changes_queued"
    },
    {
     "expr": "outstanding_changes_removed",
     "legendFormat": "{{instance}} outstanding_changes_removed"
    }
   ]
  },
  {
   "title": "prep_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prep_processor_queue_size",
     "legendFormat": "{{instance}} prep_processor_queue_size-{{quantile}}"
    },
    {
     "expr": "prep_processor_queue_size_count",
     "legendFormat": "{{instance}} prep_processor_queue_size_count"
    },
    {
     "expr": "prep_processor_queue_size_sum",
     "legendFormat": "{{instance}} prep_processor_queue_size_sum"
    }
   ]
  },
  {
   "title": "prep_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prep_process_time", "legendFormat": "{{instance}} prep_process_time" }
   ]
  },
  {
   "title": "prep_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prep_processor_request_queued",
     "legendFormat": "{{instance}} prep_processor_request_queued"
    }
   ]
  },
  { "title": "sync_processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 182 } },
  {
   "title": "sync_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_request_queued",
     "legendFormat": "{{instance}} sync_processor_request_queued"
    }
   ]
  },
  {
   "title": "sync_processor_batch_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_batch_size",
     "legendFormat": "{{instance}} sync_processor_batch_size-{{quantile}}"
    },
    {
     "expr": "sync_processor_batch_size_count",
     "legendFormat": "{{instance}} sync_processor_batch_size_count"
    },
    {
     "expr": "sync_processor_batch_size_sum",
     "legendFormat": "{{instance}} sync_processor_batch_size_sum"
    }
   ]
  },
  {
   "title": "sync_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_queue_size",
     "legendFormat": "{{instance}} sync_processor_queue_size-{{quantile}}"
    },
    {
     "expr": "sync_processor_queue_size_count",
     "legendFormat": "{{instance}} sync_processor_queue_size_count"
    },
    {
     "expr": "sync_processor_queue_size_sum",
     "legendFormat": "{{instance}} sync_processor_queue_size_sum"
    }
   ]
  },
  {
   "title": "sync_processor_queue_flush_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_queue_flush_time_ms",
     "legendFormat": "{{instance}} sync_processor_queue_flush_time_ms-{{quantile}}"
    }
   ]
  },
  {
   "title": "sync_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_process_time",
     "legendFormat": "{{instance}} sync_process_time-{{quantile}}"
    },
    {
     "expr": "sync_process_time_count",
     "legendFormat": "{{instance}} sync_process_time_count"
    },
    {
     "expr": "sync_process_time",
     "legendFormat": "{{instance}} sync_process_time_sum"
    }
   ]
  },
  { "title": "commit_processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "title": "write_batch_time_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "write_batch_time_in_commit_processor",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor-{{quantile}}"
    },
    {
     "expr": "write_batch_time_in_commit_processor_count",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor_count"
    },
    {
     "expr": "write_batch_time_in_commit_processor_sum",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor_sum"
    }
   ]
  },
  {
   "title": "write_batch_time_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "write_batch_time_in_commit_processor",
     "legendFormat": "{{instance}} -write_batch_time_in_commit_processor{{quantile}}"
    },
    {
     "expr": "write_batch_time_in_commit_processor_count",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor_count"
    },
    {
     "expr": "write_batch_time_in_commit_processor_sum",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor_sum"
    }
   ]
  },
  {
   "title": "commit_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "commit_process_time",
     "legendFormat": "{{instance}} commit_process_time-{{quantile}}"
    },
    {
     "expr": "commit_process_time_count",
     "legendFormat": "{{instance}} commit_process_time_count"
    },
    {
     "expr": "commit_process_time_sum",
     "legendFormat": "{{instance}} commit_process_time_sum"
    }
   ]
  },
  {
   "title": "read_commitproc_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "read_commitproc_time_ms",
     "legendFormat": "{{instance}} read_commitproc_time_ms-{{quantile}}"
    },
    {
     "expr": "read_commitproc_time_ms_count",
     "legendFormat": "{{instance}} read_commitproc_time_ms_count"
    },
    {
     "expr": "read_commitproc_time_ms_sum",
     "legendFormat": "{{instance}} read_commitproc_time_ms_sum"
    }
   ]
  },
  {
   "title": "read_commit_proc_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "read_commit_proc_issued",
     "legendFormat": "{{instance}} read_commit_proc_issued-{{quantile}}"
    },
    {
     "expr": "read_commit_proc_issued_count",
     "legendFormat": "{{instance}} read_commit_proc_issued_count"
    },
    {
     "expr": "read_commit_proc_issued_sum",
     "legendFormat": "{{instance}} read_commit_proc_issued_sum"
    }
   ]
  },
  {
   "title": "write_commit_proc_req_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "write_commit_proc_req_queued",
     "legendFormat": "{{instance}} write_commit_proc_req_queued"
    },
    {
     "expr": "write_commit_proc_req_queued_count",
     "legendFormat": "{{instance}} write_commit_proc_req_queued_count"
    },
    {
     "expr": "write_commit_proc_req_queued_sum",
     "legendFormat": "{{instance}} write_commit_proc_req_queued_sum"
    }
   ]
  },
  {
   "title": "write_commitproc_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "write_commitproc_time_ms",
     "legendFormat": "{{instance}} write_commitproc_time_ms"
    }
   ]
  },
  {
   "title": "request_commit_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_commit_queued",
     "legendFormat": "{{instance}} request_commit_queued"
    }
   ]
  },
  { "title": "latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 } },
  {
   "title": "updatelatency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "updatelatency",
     "legendFormat": "{{instance}} updatelatency-{{quantile}}"
    },
    {
     "expr": "updatelatency_count",
     "legendFormat": "{{instance}} updatelatency_count"
    },
    { "expr": "updatelatency_sum", "legendFormat": "{{instance}} updatelatency_sum" }
   ]
  },
  {
   "title": "max_min_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max_latency", "legendFormat": "{{instance}} max_latency" },
    { "expr": "min_latency", "legendFormat": "{{instance}} min_latency" },
    { "expr": "avg_latency", "legendFormat": "{{instance}} avg_latency" }
   ]
  },
  {
   "title": "proposal_ack_creation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proposal_ack_creation_latency",
     "legendFormat": "{{instance}} proposal_ack_creation_latency-{{quantile}}"
    }
   ]
  },
  {
   "title": "ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ack_latency",
     "legendFormat": "{{instance}} ack_latency-{{quantile}}"
    },
    { "expr": "ack_latency_count", "legendFormat": "{{instance}} ack_latency_count" },
    { "expr": "ack_latency_sum", "legendFormat": "{{instance}} ack_latency_sum" }
   ]
  },
  {
   "title": "proposal_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proposal_latency",
     "legendFormat": "{{instance}} proposal_latency-{{quantile}}"
    },
    {
     "expr": "proposal_latency_count",
     "legendFormat": "{{instance}} proposal_latency_count"
    },
    {
     "expr": "proposal_latency",
     "legendFormat": "{{instance}} proposal_latency_sum"
    }
   ]
  }
 ]
}