### Should run ping successfully
POST https://api.github.com/repos/ddieruf/apache-pulsar-helm-chart/actions/workflows/helmbot.yml/dispatches
Content-Type: application/json
Accept: application/vnd.github+json
Authorization: Bearer {{gh-token}}

{
  "ref": "create-workflows",
  "inputs": {
    "cmd": "ping",
    "log-level": "info"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}