{{- if eq .Release.IsInstall true -}}
{{- $component := "setup-cluster" -}}
{{- $name := "create-tenants-namespaces-topics" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "meta-data-store.name" $) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers: {{ include "common.lifeCycle.broker-statefulset-running" . | nindent 8 }}
      containers:
        - name: {{ $name | quote }}
          image: {{ include "common.images.image" (dict "imageRoot" .Values.global.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - "/pulsar/bin/pulsar-shell -f /pulsar/setup/setup-cluster.txt --fail-on-error"
          volumeMounts:
            - name: "setup"
              mountPath: /pulsar/setup
      volumes:
        - name: "setup"
          configMap:
            name: "setup-cluster-config"
{{- end -}}