{{- if .Release.IsInstall -}}
{{- $component := "life-cycle" -}}
{{- $name := "stage.1-storage-running" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "metadata-store.name" $) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  backoffLimit: 5
  template:
    metadata:
      name: {{ $name | quote }}
      labels: {{ include "common.labels.standard" (dict "name" $component "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: {{ $component | quote }}
    spec:
      restartPolicy: Never
      containers: {{ include "common.lifeCycle.metadata-store-running" . | nindent 8 }}
        {{ include "common.lifeCycle.data-store-running" . | nindent 8 }}
{{- end -}}