name: Add message to comment

on:
  workflow_call:
    inputs:
      message:
        required: false
        type: string
      reaction-type:
        required: false
        type: string
      repository:
        required: false
        type: string
      comment-id:
        required: false
        type: string
    secrets:
      BOT_ACTION_TOKEN:
        required: true

jobs:
  AddMessageToComment:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add message to comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_ACTION_TOKEN }}
          repository: ${{ inputs.repository }}
          comment-id: ${{ inputs.comment-id }}
          reaction-type: ${{ inputs.reaction-type }}
          body: ${{ inputs.message }}