name: Unit test component

on:
  workflow_call:
    inputs:
      component-name:
        required: true
        type: string
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ${{ env.GITHUB_WORKSPACE }}/test-repo

      - name: "Install helm 3"
        run: |
          installScript=https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          curl "$installScript" 2>/dev/null | bash >/dev/null

      - name: "Install helm unittest"
        run: helm plugin install https://github.com/quintush/helm-unittest >/dev/null 2>/dev/null

      - name: "Test component: ${{ inputs.component-name }}"
        run: ${GITHUB_WORKSPACE}/test-repo/charts/apache-pulsar/charts/${{ inputs.component-name }}/tests/test-all-templates.sh